### ISSUE TITLE
[Bug] Button alignment hardcoded with pixel values

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/cc-resource-archive#143]
## Description
The button alignment on the resource page is done using hardcode pixels which is not a good practice. Also it makes the responsiveness dependent on the dimension of buttons. Any changes made to button dimension will also require changes here. Example --> Missing repo button caused responsiveness issues.
![image](https://user-images.githubusercontent.com/91469717/229276760-8add2b8e-6beb-419d-8a88-6924061a4193.png)

Unnecessary code which can be deleted
![image](https://user-images.githubusercontent.com/91469717/229271852-a7c9f073-7d13-4985-8169-1860c909ba6f.png)
Instead of this we can use flex properties in style.css
 

## Reproduction

1. Go to [resource page](https://resources.creativecommons.org/open-data-handbook/)  
2. See error.

## Expectation
It should be properly aligned in the centre.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Xaid-vfx** [comment]
Good catch. Apparently, the misalignment of download button is only in open data handbook resource and no other.
The misalignment is not due hard coded pixels because if it were it would have been same for all resources.

Thanks to your issue, I had to take a look at it. The reason behind this is a [commit](https://github.com/creativecommons/cc-resource-archive/commit/797ed1c18d0bfcd34c4430f6177ccc3502a1ac6a) from @Keerthivardhan1 . Apparently, he was removed all repo links from resources that were not working. But due to this change in `resource.html` , the repo link of **Open data handbook which was working fine is not displayed**. So next to the download button there should be a repo button link, which is missing.

Here's the repo [url](https://github.com/okfn/opendatahandbook) that was compromised. 

If this was intentional, then I would suggest to just remove the `repourl` from `opendatahandbook.html` and the issue would be resolved.

I request @possumbilities to take a look into this as the change is live already.

**Comment by Lakshay-Pruthi** [comment]
@Xaid-vfx Thanks for the details you provided. I completely agree the misalignment is due to missing repo button but ultimately this needs to be corrected as it is not a good practice and any changes made to the download or repo button will result into misalignment in future.

**Comment by Lakshay-Pruthi** [comment]
@Xaid-vfx Updated issue title and description to address the main point.

**Comment by Keerthivardhan1** [comment]
@Lakshay-Pruthi  
under the guidance of @possumbilities I had successfully resolved all the broken links this is one from them.
I think this issue is occurring with only --> open data hand book page. 

Clicking on the button previously led to a website that is no longer available on the internet, namely lawrent.com.
we should not include the repository button again.  For additional information, please refer to https://github.com/creativecommons/cc-resource-archive/issues/11.

**Comment by Keerthivardhan1** [comment]
@Lakshay-Pruthi, you only need to organize the CSS styles, and your exploration in the website is really appreciative.

**Comment by Keerthivardhan1** [comment]
@Lakshay-Pruthi, you only need to organize the CSS styles, and your exploration in the website is really appreciative.

**Comment by Xaid-vfx** [comment]
Hey @Lakshay-Pruthi and @Keerthivardhan1,
We can carry this conversation to #144, as it addresses the issue accurately.

**Comment by abhishekshah5486** [comment]
Please assign this issue to me.

**Comment by Murdock9803** [comment]
@abhishekshah5486 The UI for the page has major improvements done, and the issue has become irrelevant since then. 
We can close the issue as completed @possumbilities 🙌

**Comment by possumbilities** [comment]
@Murdock9803 Is there a specific PR that targets this best?

**Comment by Murdock9803** [comment]
@possumbilities The PR #304 targets the UI improvement for Resource Page. The button alignment and everything is taken care of there 🙌 
[refactored the html and css for resource page](https://github.com/creativecommons/cc-resource-archive/pull/304)
