### ISSUE TITLE
[Feature] <This entire website consists of static page it requires hovering and UI finishing.> https://resources.creativecommons.org/

### ISSUE THREAD

**Issue by Lokeshsri11** [creativecommons/cc-resource-archive#149]
![Uploading 2023-04-01 (3).png…]()

**Comment by Xaid-vfx** [comment]
Hey @Lokeshsri11,
Your issue is not descriptive and precise. It's not clear what you're trying to propose.
Please read [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/#proposing-a-new-issue) for proposing an issue. Please **close this issue** and raise a new one following the guidelines.
