### ISSUE TITLE
[Feature] <This entire website consists of static page it requires hovering and UI finishing.> https://resources.creativecommons.org/

### ISSUE THREAD

**Issue by Lokeshsri11** [creativecommons/cc-resource-archive#150]
![2023-04-01 (3)](https://user-images.githubusercontent.com/93934416/229294469-a9ddf2d0-f259-407f-9a6a-5b24a4d44713.png)

**Comment by Xaid-vfx** [comment]
Hey @Lokeshsri11,
Your issue is not descriptive and precise. It's not clear what you're trying to propose.
Please read [Contribution Guidelines](https://opensource.creativecommons.org/contributing-code/#proposing-a-new-issue) for proposing an issue. Please **close this issue** and raise a new one following the guidelines.

**Comment by justaskulkarni** [comment]
You have raised the same issue twice. The previous one being #149. Also it'd be better if you elaborate a bit more on your expectation is. That would better for the maintainers to review.
