### ISSUE TITLE
[Bug] Inconsistent docker behavior - parsing Gemfile

### ISSUE THREAD

**Issue by Murdock9803** [creativecommons/cc-resource-archive#276]
## Description
While trying to preview the site from our local clone, the command `docker compose up` results in an error message while parsing the Gemfile in the last step of the Dockerfile commands, that is `RUN bundle install` .
The message  says : `failed to solve: process "/bin/sh -c bundle install" did not complete successfully: exit code:4

## Reproduction

1. Clone the repository in your local machine (main branch)
2. Change the directory to your clone in the terminal
3. In the terminal, enter the command `docker compose up`
4. See error.

## Expectation
The docker image should build as earlier it used to, by the command `docker compose up` and users should be able to have a preview of the site in their local machine storage.

## Screenshots
![error image](https://github.com/creativecommons/cc-resource-archive/assets/136724527/68972eaa-ede1-485a-a27b-8085c2639335)

## Environment

 - Device: Laptop - HP Pavillion Gaming 15
 - OS: Microsoft Windows 11 - version 10.0.22631
 - Docker version: 25.3
 - docker-compose version: v2.24.5
 - wsl version:
![Screenshot 2024-06-12 003223](https://github.com/creativecommons/cc-resource-archive/assets/136724527/5217eb8c-098d-4e5c-8b6d-0247a8ec2162)

 
## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by Murdock9803** [comment]
@possumbilities I would like to inform that the issue is created.

**Comment by possumbilities** [comment]
I was able to relatedly reproduce this on a linux dev container with VS Code `Ubuntu 20.04.6 LTS`

<img width="850" alt="Screen Shot 2024-06-10 at 10 24 56 AM" src="https://github.com/creativecommons/cc-resource-archive/assets/109087089/730e9c5c-cc74-40e6-a876-063a175c5e7c">

The error differs from the screenshot on Windows, but I suspect that the Linux error might be more accurate in determining a cause. 

After walking back through recent changes to Docker it appears that the introduction of the prettier node container introduced a breaking change to the Docker environment: 
* https://github.com/creativecommons/cc-resource-archive/pull/257

I removed these changes with a testing branch `revert-docker`, and the Docker environment runs correctly again. Ayush also tested it on Windows and it works again there as well:
* https://github.com/creativecommons/cc-resource-archive/tree/revert-docker

Digging deeper into what the cause here I found these: 

* https://forums.docker.com/t/docker-build-multistage-failed-to-compute-cache-key/134316/20
* https://github.com/docker/buildx/issues/1921

**Comment by possumbilities** [comment]
As this is a breaking change, blocking current work my plan at the moment is to clean up the `revert-docker` branch, and initiate a PR for it. We can then continue investigating what causes this Issue with the new Docker configuration with the addition of the node container, correct that and then add it back in.
